导入包

In [1]:
import torch

初始化矩阵

In [2]:
torch.empty(5, 3)

tensor([[8.9082e-39, 8.4489e-39, 9.6429e-39],
        [8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 1.0653e-38]])

构建一个随机初始化的矩阵（0， 1）

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.8428, 0.8105, 0.4788],
        [0.2182, 0.7742, 0.1745],
        [0.4747, 0.0849, 0.2694],
        [0.1952, 0.1100, 0.2185],
        [0.7185, 0.0095, 0.6582]])

生成0矩阵

In [4]:
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

打印数据类型

In [5]:
x.dtype

torch.float32

改变数据类型

In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
x.dtype
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [9]:
x = torch.zeros(5, 3).long()
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

直接从数据构造tensor

In [10]:
x = torch.tensor([2, 3, 4])
x

tensor([2, 3, 4])

生成形状相同的数组

In [11]:
y = torch.randn_like(x, dtype=torch.float)
y

tensor([-1.1205,  1.4723, -1.1820])

得到tensor形状(返回为tuple)

In [12]:
x.size()

torch.Size([3])

加法运算

In [13]:
y = torch.rand(5, 3)
x = torch.rand(5, 3)
x + y

tensor([[0.7819, 0.8668, 1.4589],
        [0.5144, 0.7873, 1.5997],
        [1.1603, 0.4174, 0.5717],
        [1.4554, 1.1888, 1.5368],
        [0.9939, 1.5671, 0.3933]])

In [14]:
torch.add(x, y)

tensor([[0.7819, 0.8668, 1.4589],
        [0.5144, 0.7873, 1.5997],
        [1.1603, 0.4174, 0.5717],
        [1.4554, 1.1888, 1.5368],
        [0.9939, 1.5671, 0.3933]])

把输出作为一个变量

In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[0.7819, 0.8668, 1.4589],
        [0.5144, 0.7873, 1.5997],
        [1.1603, 0.4174, 0.5717],
        [1.4554, 1.1888, 1.5368],
        [0.9939, 1.5671, 0.3933]])

in-place加法

In [17]:
y.add_(x)
y

tensor([[0.7819, 0.8668, 1.4589],
        [0.5144, 0.7873, 1.5997],
        [1.1603, 0.4174, 0.5717],
        [1.4554, 1.1888, 1.5368],
        [0.9939, 1.5671, 0.3933]])

index操作

In [19]:
x[:, 1:]
x[2:, :2]

tensor([[0.2650, 0.3315],
        [0.8765, 0.6268],
        [0.3033, 0.6482]])

reshape/resize

In [24]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(2, 8)
z
# y

tensor([[-1.1246, -0.7117, -0.0436,  0.7541, -0.8019, -0.0503, -0.9123, -0.6107],
        [-0.9189,  0.0911, -1.9705, -0.2976, -0.3787, -0.6509,  0.2882,  0.1093]])

返回数字/当只有一个元素时

In [26]:
x = torch.randn(1)
x.item()

-1.3593435287475586

Numpy和Tensor之间的转换

In [27]:
a = torch.randn(5, 4)
a
b = a.numpy()
b

array([[-0.1003732 , -0.702996  , -2.0463161 ,  0.89925796],
       [-1.1159297 ,  0.47158164,  0.6499608 , -0.62889826],
       [-0.45231813, -0.9063362 ,  1.0291758 ,  0.37051845],
       [ 0.6584637 , -1.127875  , -0.10453621,  0.5100557 ],
       [-1.0118613 ,  1.3333318 , -0.3961412 ,  0.06299078]],
      dtype=float32)

In [30]:
import numpy as np
a = np.ones([5, 5])
b = torch.from_numpy(a)
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

CUDA Tensors

In [32]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)

tensor([-0.3593], device='cuda:0')


In [33]:
z.to("cpu").data.numpy()
z.cpu().data.numpy()

array([-0.35934353], dtype=float32)